global:
  imageRegistry: "268015775379.dkr.ecr.us-east-1.amazonaws.com"
  imageTag: "dev-9"
  namespace: dev
  springProfile: docker
  configServerUrl: "http://config-server:8888"
  eurekaDefaultZone: "http://discovery-server:8761/eureka/"
api-gateway:
  service:
    type: LoadBalancer
genai-service:
  replicaCount: 0
